import { stableStringify } from "./stable_json.js";

export const anthropicProfileV0RequiredFiles = [
  "CLAUDE.md",
  "MOVA.md",
  ".claude/settings.json",
  ".claude/commands/mova_context.md",
  ".claude/commands/mova_lint.md",
  ".claude/skills/mova-layer-v0/SKILL.md",
] as const;

export function getAnthropicProfileV0Files(): Record<string, string> {
  return {
    "CLAUDE.md": [
      "# CLAUDE",
      "",
      "This profile is generated by mova-claude-import.",
      "",
      "Use MOVA.md for the project rules and structure.",
      "Use .claude/commands/mova_context.md to build context.",
      "Use .claude/commands/mova_lint.md to run structural lint.",
      "",
    ].join("\n"),
    "MOVA.md": [
      "# MOVA",
      "",
      "This is a clean Anthropic profile v0 output.",
      "",
      "Artifacts:",
      "- mova/claude_import/v0/import_manifest.json",
      "- mova/claude_import/v0/redaction_report.json",
      "- mova/claude_import/v0/lint_report_v0.json",
      "- mova/claude_import/v0/contracts/*.json",
      "- mova/claude_import/v0/episode_import_run.json",
      "",
    ].join("\n"),
    ".claude/settings.json": stableStringify({
      profile_version: "v0",
      commands: ["mova_context", "mova_lint"],
      skills_root: ".claude/skills",
    }) + "\n",
    ".claude/commands/mova_context.md": [
      "# mova_context",
      "",
      "Summarize the project based on MOVA.md and the contracts in",
      "mova/claude_import/v0/contracts.",
      "",
    ].join("\n"),
    ".claude/commands/mova_lint.md": [
      "# mova_lint",
      "",
      "Run structural checks and report results from",
      "mova/claude_import/v0/lint_report_v0.json.",
      "",
    ].join("\n"),
    ".claude/skills/mova-layer-v0/SKILL.md": [
      "---",
      "name: mova-layer-v0",
      "version: v0",
      "---",
      "",
      "# mova-layer-v0",
      "",
      "Baseline behavior for the Anthropic profile v0 output.",
      "",
    ].join("\n"),
  };
}
